"""empty message

Revision ID: 55952b368b4f
Revises: 82896d5e70e1
Create Date: 2019-05-08 18:23:09.939619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55952b368b4f'
down_revision = '82896d5e70e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', sa.String(length=40), nullable=True))
    op.create_unique_constraint(None, 'users', ['token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'token')
    # ### end Alembic commands ###
