"""empty message

Revision ID: 82896d5e70e1
Revises: f735251a828a
Create Date: 2019-05-07 15:10:26.173239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82896d5e70e1'
down_revision = 'f735251a828a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('password', table_name='users')
    op.drop_index('phone_number', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('phone_number', 'users', ['phone_number'], unique=True)
    op.create_index('password', 'users', ['password'], unique=True)
    # ### end Alembic commands ###
