"""empty message

Revision ID: 83c629bc4b66
Revises: a844efc4243d
Create Date: 2019-05-08 20:49:22.674481

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83c629bc4b66'
down_revision = 'a844efc4243d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('google_id', table_name='users')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', mysql.VARCHAR(length=40), nullable=True))
    op.create_index('google_id', 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###
