"""empty message

Revision ID: f735251a828a
Revises: 
Create Date: 2019-04-28 14:06:27.135099

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f735251a828a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('cinemas', 'created_at')
    op.drop_column('cinemas', 'updated_at')
    op.drop_column('movies', 'created_at')
    op.drop_column('movies', 'updated_at')
    op.drop_column('showtimes', 'created_at')
    op.drop_column('showtimes', 'updated_at')
    op.create_foreign_key(None, 'theater_tickets', 'theaters', ['theater_id'], ['id'])
    op.drop_column('theater_tickets', 'created_at')
    op.drop_column('theater_tickets', 'updated_at')
    op.drop_column('theaters', 'created_at')
    op.drop_column('theaters', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('theaters', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('theaters', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('theater_tickets', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('theater_tickets', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.drop_constraint(None, 'theater_tickets', type_='foreignkey')
    op.add_column('showtimes', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('showtimes', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('movies', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('movies', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('cinemas', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('cinemas', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.drop_table('tests')
    # ### end Alembic commands ###
